name: Docker build

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      artifacts-name:
        description: "The name of the artifacts to download"
        required: false
        type: string
      context-path:
        description: "The path to the Docker build context"
        required: false
        type: string
        default: "."
      dockerfile-path:
        description: "The path to the Dockerfile"
        required: false
        type: string
        default: "Dockerfile"
      checkout-ref:
        description: "The git ref to checkout"
        type: string
        default: ""

permissions:
  contents: read
  packages: write
  # id-token: write

env:
  REGISTRY: "ghcr.io"

jobs:
  docker-build:
    runs-on: namespace-profile-small-amd64
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.checkout-ref }}
      - name: Set GitHub slug environment variables
        uses: rlespinasse/github-slug-action@ef93b2ea4b6405d06fd8684fc3ff795d262ecae8 # v5.7.0
      # TODO: Migrate to Artifact Registry org-wide
      # - name: Authenticate to Google Cloud
      #   id: auth
      #   uses: google-github-actions/auth@v3
      #   with:
      #     project_id: x
      #     workload_identity_provider: "projects/x/locations/global/workloadIdentityPools/github/providers/actions"
      #     service_account: "github-actions@x.iam.gserviceaccount.com"
      #     token_format: "access_token"
      # - name: Log in to registry
      #   uses: docker/login-action@v4
      #   with:
      #     username: oauth2accesstoken
      #     password: ${{ steps.auth.outputs.access_token }}
      #     registry: ${{ env.REGISTRY }}
      - uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@bb05f3f5519dd87d3ba754cc423b652a5edd6d2c # v4.2.0
      - name: Download artifacts
        uses: namespace-actions/download-artifact@7cbad919e4b0e09f17e9d6311a444ff002992b5b # v1.0.3
        with:
          name: ${{ inputs.artifacts-name }}
        if: ${{ inputs.artifacts-name != '' }}
      - name: Generate Docker image metadata
        id: docker-meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        env:
          # GitHub Packages requires annotations metadata in at least the index descriptor to show them
          # up properly in its UI it seems, but it's not clear about it, because the docs refer to the
          # image manifest only. See:
          # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#adding-a-description-to-multi-arch-images
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: ${{ env.REGISTRY }}/modrinth/${{ inputs.image-name }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.GITHUB_REF_SLUG }}-gh${{ github.run_id }}
            type=raw,value=gh${{ github.run_id }}
      - name: Build and push Docker image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: ${{ inputs.context-path }}
          file: ${{ inputs.dockerfile-path }}
          push: ${{ github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository }}
          tags: ${{ steps.docker-meta.outputs.tags }}
          labels: ${{ steps.docker-meta.outputs.labels }}
          annotations: ${{ steps.docker-meta.outputs.annotations }}
          build-args: |
            APPLICATION_NAME=${{ inputs.image-name }}
            GIT_HASH=${{ fromJSON(steps.docker-meta.outputs.json).labels['org.opencontainers.image.revision'] }}
